# Generated by Django 6.0.5 on 2026-05-15 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono"
                    ),
                ),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
            ],
            options={
                "verbose_name": "Administrativo",
                "verbose_name_plural": "Administrativos",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono"
                    ),
                ),
                ("fecha_contrato", models.DateField(verbose_name="Fecha de contrato")),
                (
                    "especialidad",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Especialidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
            },
        ),
    ]
