# Generated by Django 6.0.5 on 2026-05-15 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE", "Ausente"),
                            ("ATRASO", "Atraso"),
                            ("JUSTIFICADO", "Justificado"),
                        ],
                        default="PRESENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="Observación"),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del curso"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("año", models.IntegerField(verbose_name="Año académico")),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-año", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_matricula",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de matrícula"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(7.0),
                        ],
                        verbose_name="Nota",
                    ),
                ),
                (
                    "tipo_nota",
                    models.CharField(
                        choices=[
                            ("PRUEBA", "Prueba"),
                            ("TAREA", "Tarea"),
                            ("EXAMEN", "Examen"),
                            ("TRABAJO", "Trabajo"),
                            ("CONTROL", "Control"),
                            ("OTRO", "Otro"),
                        ],
                        default="PRUEBA",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="Observación"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "ordering": ["nombre"],
            },
        ),
    ]
