# Generated by Django 6.0.5 on 2026-05-15 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.course"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.student"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="alumnos",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                through="academics.Enrollment",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades_given",
                to="accounts.teacher",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="cursos",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="academics.course"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="profesores",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="accounts.teacher"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="academics.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "course", "fecha")},
        ),
    ]
